# Generated by Django 5.0.3 on 2024-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(choices=[('MED1', 'med1'), ('MED2', 'med2'), ('MED3', 'med3')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='price',
            field=models.DecimalField(choices=[], decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
